# Generated by Django 5.1.6 on 2025-03-12 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DigitizingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('colors', models.IntegerField(blank=True, null=True)),
                ('po_number', models.IntegerField(blank=True, null=True)),
                ('file_format', models.CharField(blank=True, choices=[('100', '100'), ('cnd', 'cnd'), ('dsb', 'dsb'), ('dst', 'dst'), ('dsz', 'dsz'), ('emb', 'emb'), ('exp', 'exp'), ('jef', 'jef'), ('ksm', 'ksm'), ('pes', 'pes'), ('pof', 'pof'), ('tap', 'tap'), ('xxx', 'xxx'), ('ofm', 'ofm'), ('pxf', 'pxf'), ('sus', 'sus'), ('hus', 'hus'), ('ngs', 'ngs'), ('Others', 'Others')], max_length=10, null=True)),
                ('fabric_type', models.CharField(blank=True, choices=[('Cotton', 'Cotton'), ('Silk', 'Silk'), ('Wool', 'Wool')], max_length=50, null=True)),
                ('logo_placement', models.CharField(blank=True, choices=[('Left', 'Left'), ('Right', 'Right'), ('Back', 'Back')], max_length=50, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DigitizingOrder_Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='digitizing_order_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='crafting.digitizingorder')),
            ],
        ),
    ]
