# Generated by Django 5.1.6 on 2025-09-28 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crafting', '0001_initial'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='digitizingorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digitizing_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='digitizingorder_files',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='crafting.digitizingorder'),
        ),
        migrations.AddField(
            model_name='digitizingorderedit',
            name='original_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='crafting.digitizingorder'),
        ),
        migrations.AddField(
            model_name='digitizingquote',
            name='converted_to_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_quote', to='crafting.digitizingorder'),
        ),
        migrations.AddField(
            model_name='digitizingquote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digitizing_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='digitizingquote_files',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='crafting.digitizingquote'),
        ),
        migrations.AddField(
            model_name='finalizeddigitizingorder',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digitizing_finalization', to='finance.invoice'),
        ),
        migrations.AddField(
            model_name='finalizeddigitizingorder',
            name='original_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finalized_version', to='crafting.digitizingorder'),
        ),
        migrations.AddField(
            model_name='finalizeddigitizingfiles',
            name='finalized_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digitizing_files', to='crafting.finalizeddigitizingorder'),
        ),
        migrations.AddField(
            model_name='finalizedvectororder',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vector_finalization', to='finance.invoice'),
        ),
        migrations.AddField(
            model_name='finalizedvectorfiles',
            name='finalized_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vector_files', to='crafting.finalizedvectororder'),
        ),
        migrations.AddField(
            model_name='patchorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patch_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finalizedpatchfiles',
            name='finalized_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patch_files', to='crafting.patchorder'),
        ),
        migrations.AddField(
            model_name='patchorder_files',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='crafting.patchorder'),
        ),
        migrations.AddField(
            model_name='patchorderedit',
            name='original_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='crafting.patchorder'),
        ),
        migrations.AddField(
            model_name='patchquote',
            name='converted_to_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_quote', to='crafting.patchorder'),
        ),
        migrations.AddField(
            model_name='patchquote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patch_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patchquote_files',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='crafting.patchquote'),
        ),
        migrations.AddField(
            model_name='vectororder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vector_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finalizedvectororder',
            name='original_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finalized_version', to='crafting.vectororder'),
        ),
        migrations.AddField(
            model_name='vectororder_files',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='crafting.vectororder'),
        ),
        migrations.AddField(
            model_name='vectororderedit',
            name='original_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='crafting.vectororder'),
        ),
        migrations.AddField(
            model_name='vectorquote',
            name='converted_to_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_quote', to='crafting.vectororder'),
        ),
        migrations.AddField(
            model_name='vectorquote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vector_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vectorquote_files',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='crafting.vectorquote'),
        ),
    ]
