# Generated by Django 5.1.6 on 2025-03-19 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatchOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('po_number', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('patch_type', models.CharField(blank=True, choices=[('3D Puff Patches', '3D Puff Patches'), ('Applique Patches', 'Applique Patches'), ('Blank Patches', 'Blank Patches'), ('Chenille Patches', 'Chenille Patches'), ('Embroidered Patches', 'Embroidered Patches')], max_length=50, null=True)),
                ('backing_type', models.CharField(blank=True, choices=[('Iron On (Heat Seal)', 'Iron On (Heat Seal)'), ('Velcro (Both Hook & Loop)', 'Velcro (Both Hook & Loop)')], max_length=50, null=True)),
                ('border_type', models.CharField(blank=True, choices=[('Hot Cut Border', 'Hot Cut Border'), ('Merrowed Border', 'Merrowed Border')], max_length=50, null=True)),
                ('embroidery_fill', models.CharField(blank=True, choices=[('50% Embroidery', '50% Embroidery'), ('75% Embroidery', '75% Embroidery'), ('10% Embroidery', '100% Embroidery')], max_length=50, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('date', models.DateField()),
                ('color_details', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=50)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Pending', 'Pending'), ('On Hold', 'On Hold'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Processing', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VectorOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('po_number', models.IntegerField(blank=True, null=True)),
                ('required_format', models.CharField(choices=[('cdr', 'cdr'), ('ai', 'ai'), ('eps', 'eps'), ('others', 'others')], max_length=50)),
                ('color_types', models.CharField(choices=[('PMS', 'PMS'), ('RGB', 'RGB'), ('CMYK', 'CMYK')], max_length=50)),
                ('colors', models.IntegerField(default=1)),
                ('others', models.CharField(blank=True, max_length=255, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Pending', 'Pending'), ('On Hold', 'On Hold'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Processing', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='digitizingorder',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Pending', 'Pending'), ('On Hold', 'On Hold'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Processing', max_length=50),
        ),
        migrations.AlterField(
            model_name='digitizingorder',
            name='fabric_type',
            field=models.CharField(blank=True, choices=[('Apron', 'Apron'), ('Beanie', 'Beanie'), ('Blanket', 'Blanket'), ('Canvas', 'Canvas'), ('Chenille', 'Chenille'), ('Cotton Woven', 'Cotton Woven'), ('Denim', 'Denim'), ('Felt', 'Felt'), ('Flannel', 'Flannel'), ('Fleece', 'Fleece'), ('Knit Sweater', 'Knit Sweater'), ('Leather', 'Leather'), ('Mesh Knit', 'Mesh Knit'), ('Nylon', 'Nylon'), ('Others', 'Others'), ('Pique', 'Pique'), ('Polar Fleece', 'Polar Fleece'), ('Polyester', 'Polyester')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='digitizingorder',
            name='logo_placement',
            field=models.CharField(blank=True, choices=[('Apron', 'Apron'), ('Back Applique', 'Back Applique'), ('Bags', 'Bags'), ('Beanie Caps', 'Beanie Caps'), ('Cap', 'Cap'), ('Cap Back', 'Cap Back'), ('Cap Puff', 'Cap Puff'), ('Cap Side', 'Cap Side'), ('Chest', 'Chest'), ('Chest Applique', 'Chest Applique'), ('Full Front Chest', 'Full Front Chest'), ('Gloves', 'Gloves'), ('Jacket Back', 'Jacket Back'), ('Others', 'Others'), ('Patches', 'Patches'), ('Sleeve', 'Sleeve'), ('Table Cloth', 'Table Cloth'), ('Towel', 'Towel')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='PatchOrder_Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='patch_order_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='crafting.patchorder')),
            ],
        ),
        migrations.CreateModel(
            name='VectorOrder_Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='vector_order_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='crafting.vectororder')),
            ],
        ),
    ]
