# Generated by Django 5.1.6 on 2025-04-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0005_alter_digitizingorder_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patchorder',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='patchorder',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
