# Generated by Django 5.1.6 on 2025-04-12 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0006_alter_patchorder_height_alter_patchorder_width'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('credit', 'Credit Card'), ('paypal', 'PayPal'), ('bank', 'Bank Transfer'), ('cashApp', 'CashApp')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('digitizing_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crafting.digitizingorder')),
                ('patch_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crafting.patchorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vector_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crafting.vectororder')),
            ],
        ),
    ]
