# Generated by Django 5.1.6 on 2025-04-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0008_remove_payment_digitizing_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('credit', 'Credit Card'), ('paypal', 'PayPal'), ('bank', 'Bank Transfer'), ('cash', 'Cash')], max_length=20),
        ),
    ]
