# Generated by Django 5.1.6 on 2025-04-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0010_digitizingorder_price_patchorder_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitizingorder',
            name='stiches',
            field=models.IntegerField(default=0),
        ),
    ]
