# Generated by Django 5.1.6 on 2025-04-28 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0011_digitizingorder_stiches'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digitizingorder',
            old_name='stiches',
            new_name='stitches',
        ),
    ]
