# Generated by Django 5.1.6 on 2025-04-28 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0012_rename_stiches_digitizingorder_stitches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetail',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='paymentdetail',
            name='digitizing_order',
        ),
        migrations.RemoveField(
            model_name='paymentdetail',
            name='patch_order',
        ),
        migrations.RemoveField(
            model_name='paymentdetail',
            name='vector_order',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PaymentDetail',
        ),
    ]
