# Generated by Django 5.1.6 on 2025-05-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0013_remove_paymentdetail_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitizingorder',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='digitizingorder',
            name='stitches',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='digitizingorder',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
