# Generated by Django 5.1.6 on 2025-05-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0014_alter_digitizingorder_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitizingorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='patchorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='vectororder',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
