# Generated by Django 5.1.6 on 2025-05-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0015_digitizingorder_order_number_patchorder_order_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitizingorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='patchorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='vectororder',
            name='order_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
