# Generated by Django 5.1.6 on 2025-05-27 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0017_alter_digitizingorder_order_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitizingquote',
            name='converted_to_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_quote', to='crafting.digitizingorder'),
        ),
        migrations.AddField(
            model_name='digitizingquote',
            name='po_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='digitizingquote',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='digitizingquote',
            name='quote_status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Quoted', 'Quoted'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Requested', max_length=50),
        ),
        migrations.AddField(
            model_name='digitizingquote',
            name='stitches',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='patchquote',
            name='converted_to_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_quote', to='crafting.patchorder'),
        ),
        migrations.AddField(
            model_name='patchquote',
            name='po_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patchquote',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='patchquote',
            name='quote_status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Quoted', 'Quoted'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Requested', max_length=50),
        ),
        migrations.AddField(
            model_name='vectorquote',
            name='converted_to_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_quote', to='crafting.vectororder'),
        ),
        migrations.AddField(
            model_name='vectorquote',
            name='po_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vectorquote',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vectorquote',
            name='quote_status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Quoted', 'Quoted'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Requested', max_length=50),
        ),
        migrations.AlterField(
            model_name='digitizingquote',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='digitizingquote',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='patchquote',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='patchquote',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.CreateModel(
            name='DigitizingQuote_Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='digitizing_quote_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='crafting.digitizingquote')),
            ],
        ),
        migrations.CreateModel(
            name='PatchQuote_Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='patch_quote_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='crafting.patchquote')),
            ],
        ),
        migrations.CreateModel(
            name='VectorQuote_Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='vector_quote_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='crafting.vectorquote')),
            ],
        ),
    ]
