# Generated by Django 5.1.6 on 2025-06-09 17:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0018_digitizingquote_converted_to_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalizedDigitizingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalized_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stitches', models.IntegerField(blank=True, null=True)),
                ('colors', models.IntegerField(blank=True, null=True)),
                ('po_number', models.IntegerField(blank=True, null=True)),
                ('file_format', models.CharField(blank=True, choices=[('100', '100'), ('cnd', 'cnd'), ('dsb', 'dsb'), ('dst', 'dst'), ('dsz', 'dsz'), ('emb', 'emb'), ('exp', 'exp'), ('jef', 'jef'), ('ksm', 'ksm'), ('pes', 'pes'), ('pof', 'pof'), ('tap', 'tap'), ('xxx', 'xxx'), ('ofm', 'ofm'), ('pxf', 'pxf'), ('sus', 'sus'), ('hus', 'hus'), ('ngs', 'ngs'), ('Others', 'Others')], max_length=10, null=True)),
                ('fabric_type', models.CharField(blank=True, choices=[('Apron', 'Apron'), ('Beanie', 'Beanie'), ('Blanket', 'Blanket'), ('Canvas', 'Canvas'), ('Chenille', 'Chenille'), ('Cotton Woven', 'Cotton Woven'), ('Denim', 'Denim'), ('Felt', 'Felt'), ('Flannel', 'Flannel'), ('Fleece', 'Fleece'), ('Knit Sweater', 'Knit Sweater'), ('Leather', 'Leather'), ('Mesh Knit', 'Mesh Knit'), ('Nylon', 'Nylon'), ('Others', 'Others'), ('Pique', 'Pique'), ('Polar Fleece', 'Polar Fleece'), ('Polyester', 'Polyester')], max_length=50, null=True)),
                ('logo_placement', models.CharField(blank=True, choices=[('Apron', 'Apron'), ('Back Applique', 'Back Applique'), ('Bags', 'Bags'), ('Beanie Caps', 'Beanie Caps'), ('Cap', 'Cap'), ('Cap Back', 'Cap Back'), ('Cap Puff', 'Cap Puff'), ('Cap Side', 'Cap Side'), ('Chest', 'Chest'), ('Chest Applique', 'Chest Applique'), ('Full Front Chest', 'Full Front Chest'), ('Gloves', 'Gloves'), ('Jacket Back', 'Jacket Back'), ('Others', 'Others'), ('Patches', 'Patches'), ('Sleeve', 'Sleeve'), ('Table Cloth', 'Table Cloth'), ('Towel', 'Towel')], max_length=50, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Pending', 'Pending'), ('On Hold', 'On Hold'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField()),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('completed_date', models.DateField()),
                ('final_files', models.FileField(blank=True, null=True, upload_to='finalized/digitizing/')),
                ('finalized_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_digitizing_orders', to=settings.AUTH_USER_MODEL)),
                ('original_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finalized_version', to='crafting.digitizingorder')),
            ],
        ),
        migrations.CreateModel(
            name='FinalizedPatchOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalized_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('po_number', models.IntegerField(blank=True, null=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('patch_type', models.CharField(blank=True, choices=[('3D Puff Patches', '3D Puff Patches'), ('Applique Patches', 'Applique Patches'), ('Blank Patches', 'Blank Patches'), ('Chenille Patches', 'Chenille Patches'), ('Embroidered Patches', 'Embroidered Patches')], max_length=50, null=True)),
                ('backing_type', models.CharField(blank=True, choices=[('Iron On (Heat Seal)', 'Iron On (Heat Seal)'), ('Velcro (Both Hook & Loop)', 'Velcro (Both Hook & Loop)')], max_length=50, null=True)),
                ('border_type', models.CharField(blank=True, choices=[('Hot Cut Border', 'Hot Cut Border'), ('Merrowed Border', 'Merrowed Border')], max_length=50, null=True)),
                ('embroidery_fill', models.CharField(blank=True, choices=[('50% Embroidery', '50% Embroidery'), ('75% Embroidery', '75% Embroidery'), ('10% Embroidery', '100% Embroidery')], max_length=50, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('date', models.DateField()),
                ('color_details', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=50)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Pending', 'Pending'), ('On Hold', 'On Hold'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField()),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('shipping_date', models.DateField(blank=True, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('final_files', models.FileField(blank=True, null=True, upload_to='finalized/patch/')),
                ('finalized_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_patch_orders', to=settings.AUTH_USER_MODEL)),
                ('original_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finalized_version', to='crafting.patchorder')),
            ],
        ),
        migrations.CreateModel(
            name='FinalizedVectorOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalized_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('po_number', models.IntegerField(blank=True, null=True)),
                ('required_format', models.CharField(choices=[('cdr', 'cdr'), ('ai', 'ai'), ('eps', 'eps'), ('others', 'others')], max_length=50)),
                ('color_types', models.CharField(choices=[('PMS', 'PMS'), ('RGB', 'RGB'), ('CMYK', 'CMYK')], max_length=50)),
                ('colors', models.IntegerField(default=1)),
                ('others', models.CharField(blank=True, max_length=255, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Pending', 'Pending'), ('On Hold', 'On Hold'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField()),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('final_files', models.FileField(blank=True, null=True, upload_to='finalized/vector/')),
                ('revisions', models.PositiveIntegerField(default=0)),
                ('finalized_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_vector_orders', to=settings.AUTH_USER_MODEL)),
                ('original_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finalized_version', to='crafting.vectororder')),
            ],
        ),
    ]
