# Generated by Django 5.1.6 on 2025-06-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0019_finalizeddigitizingorder_finalizedpatchorder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitizingorder',
            name='price',
        ),
        migrations.RemoveField(
            model_name='patchorder',
            name='price',
        ),
        migrations.RemoveField(
            model_name='vectororder',
            name='price',
        ),
        migrations.AddField(
            model_name='digitizingorder',
            name='admin_instruction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patchorder',
            name='admin_instruction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vectororder',
            name='admin_instruction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
