# Generated by Django 5.1.6 on 2025-06-10 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0020_remove_digitizingorder_price_remove_patchorder_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalizeddigitizingorder',
            name='final_files',
        ),
        migrations.AlterField(
            model_name='finalizeddigitizingorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='FinalizedDigitizingFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='finalized/digitizing/files/')),
                ('file_type', models.CharField(choices=[('DESIGN', 'Final Design File'), ('STITCH', 'Stitch File'), ('COLOR', 'Color Sheet'), ('ADDITIONAL', 'Additional File')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('finalized_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_files', to='crafting.finalizeddigitizingorder')),
            ],
        ),
    ]
