# Generated by Django 5.1.6 on 2025-06-10 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0021_remove_finalizeddigitizingorder_final_files_and_more'),
        ('finance', '0003_remove_invoice_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalizeddigitizingorder',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digitizing_finalization', to='finance.invoice'),
        ),
    ]
