# Generated by Django 5.1.6 on 2025-06-16 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0022_finalizeddigitizingorder_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalizeddigitizingfiles',
            name='finalized_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digitizing_files', to='crafting.finalizeddigitizingorder'),
        ),
        migrations.AlterField(
            model_name='finalizedpatchorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='finalizedvectororder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='FinalizedPatchFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='finalized/patch/files/')),
                ('file_type', models.CharField(choices=[('DESIGN', 'Final Design File'), ('STITCH', 'Stitch File'), ('COLOR', 'Color Sheet'), ('PROOF', 'Production Proof'), ('ADDITIONAL', 'Additional File')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('finalized_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patch_files', to='crafting.finalizedpatchorder')),
            ],
        ),
        migrations.CreateModel(
            name='FinalizedVectorFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='finalized/vector/files/')),
                ('file_type', models.CharField(choices=[('VECTOR', 'Final Vector File'), ('SOURCE', 'Source File'), ('PROOF', 'Approval Proof'), ('REVISION', 'Revision File'), ('ADDITIONAL', 'Additional File')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('finalized_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vector_files', to='crafting.finalizedvectororder')),
            ],
        ),
    ]
