# Generated by Django 5.1.6 on 2025-07-01 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0023_alter_finalizeddigitizingfiles_finalized_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalizeddigitizingorder',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='finalizeddigitizingorder',
            name='fabric_type',
        ),
        migrations.RemoveField(
            model_name='finalizeddigitizingorder',
            name='file_format',
        ),
        migrations.RemoveField(
            model_name='finalizeddigitizingorder',
            name='finalized_at',
        ),
        migrations.RemoveField(
            model_name='finalizeddigitizingorder',
            name='finalized_by',
        ),
        migrations.RemoveField(
            model_name='finalizeddigitizingorder',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='finalizeddigitizingorder',
            name='is_urgent',
        ),
        migrations.RemoveField(
            model_name='finalizeddigitizingorder',
            name='logo_placement',
        ),
        migrations.RemoveField(
            model_name='finalizeddigitizingorder',
            name='name',
        ),
        migrations.RemoveField(
            model_name='finalizeddigitizingorder',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='finalizeddigitizingorder',
            name='po_number',
        ),
        migrations.RemoveField(
            model_name='finalizeddigitizingorder',
            name='status',
        ),
        migrations.CreateModel(
            name='DigitizingOrderEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('po_number', models.CharField(blank=True, max_length=50, null=True)),
                ('width', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('colors', models.IntegerField(blank=True, null=True)),
                ('logo_placement', models.CharField(blank=True, max_length=255, null=True)),
                ('fabric_type', models.CharField(blank=True, max_length=255, null=True)),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('original_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='crafting.digitizingorder')),
            ],
        ),
    ]
