# Generated by Django 5.1.6 on 2025-07-01 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0024_remove_finalizeddigitizingorder_colors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalizedpatchfiles',
            name='finalized_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patch_files', to='crafting.patchorder'),
        ),
        migrations.RemoveField(
            model_name='finalizedvectororder',
            name='color_types',
        ),
        migrations.RemoveField(
            model_name='finalizedvectororder',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='finalizedvectororder',
            name='finalized_by',
        ),
        migrations.RemoveField(
            model_name='finalizedvectororder',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='finalizedvectororder',
            name='name',
        ),
        migrations.RemoveField(
            model_name='finalizedvectororder',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='finalizedvectororder',
            name='others',
        ),
        migrations.RemoveField(
            model_name='finalizedvectororder',
            name='po_number',
        ),
        migrations.RemoveField(
            model_name='finalizedvectororder',
            name='required_format',
        ),
        migrations.RemoveField(
            model_name='finalizedvectororder',
            name='status',
        ),
        migrations.DeleteModel(
            name='FinalizedPatchOrder',
        ),
    ]
