# Generated by Django 5.1.6 on 2025-07-28 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0025_alter_finalizedpatchfiles_finalized_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patchorder',
            name='embroidery_fill',
            field=models.CharField(blank=True, choices=[('50% Embroidery', '50% Embroidery'), ('75% Embroidery', '75% Embroidery'), ('100% Embroidery', '100% Embroidery')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patchquote',
            name='embroidery_fill',
            field=models.CharField(blank=True, choices=[('50% Embroidery', '50% Embroidery'), ('75% Embroidery', '75% Embroidery'), ('100% Embroidery', '100% Embroidery')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='PatchOrderEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('po_number', models.IntegerField(blank=True, null=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('patch_type', models.CharField(blank=True, choices=[('3D Puff Patches', '3D Puff Patches'), ('Applique Patches', 'Applique Patches'), ('Blank Patches', 'Blank Patches'), ('Chenille Patches', 'Chenille Patches'), ('Embroidered Patches', 'Embroidered Patches')], max_length=50, null=True)),
                ('backing_type', models.CharField(blank=True, choices=[('Iron On (Heat Seal)', 'Iron On (Heat Seal)'), ('Velcro (Both Hook & Loop)', 'Velcro (Both Hook & Loop)')], max_length=50, null=True)),
                ('border_type', models.CharField(blank=True, choices=[('Hot Cut Border', 'Hot Cut Border'), ('Merrowed Border', 'Merrowed Border')], max_length=50, null=True)),
                ('embroidery_fill', models.CharField(blank=True, choices=[('50% Embroidery', '50% Embroidery'), ('75% Embroidery', '75% Embroidery'), ('100% Embroidery', '100% Embroidery')], max_length=50, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('color_details', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=50)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('original_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='crafting.patchorder')),
            ],
        ),
        migrations.CreateModel(
            name='VectorOrderEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('po_number', models.IntegerField(blank=True, null=True)),
                ('required_format', models.CharField(choices=[('cdr', 'cdr'), ('ai', 'ai'), ('eps', 'eps'), ('others', 'others')], max_length=50)),
                ('color_types', models.CharField(choices=[('PMS', 'PMS'), ('RGB', 'RGB'), ('CMYK', 'CMYK')], max_length=50)),
                ('colors', models.IntegerField(default=1)),
                ('others', models.CharField(blank=True, max_length=255, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('original_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='crafting.vectororder')),
            ],
        ),
    ]
