# Generated by Django 5.1.6 on 2025-07-28 11:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0026_alter_patchorder_embroidery_fill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patchorderedit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vectororderedit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
