# Generated by Django 5.1.6 on 2025-07-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0027_patchorderedit_created_at_vectororderedit_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='patchorderedit',
            name='status',
            field=models.CharField(blank=True, choices=[('Processing', 'Processing'), ('Pending', 'Pending'), ('On Hold', 'On Hold'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Processing', max_length=50),
        ),
        migrations.AddField(
            model_name='vectororderedit',
            name='status',
            field=models.CharField(blank=True, choices=[('Processing', 'Processing'), ('Pending', 'Pending'), ('On Hold', 'On Hold'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Processing', max_length=50),
        ),
    ]
