# Generated by Django 5.1.6 on 2025-07-28 11:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0028_patchorderedit_status_vectororderedit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitizingorderedit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='digitizingorderedit',
            name='status',
            field=models.CharField(blank=True, choices=[('Processing', 'Processing'), ('Pending', 'Pending'), ('On Hold', 'On Hold'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Processing', max_length=50),
        ),
    ]
