# Generated by Django 5.1.6 on 2025-07-29 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0029_digitizingorderedit_created_at_and_more'),
        ('finance', '0005_rename_date_payment_payment_date_payment_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalizedvectororder',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vector_finalization', to='finance.invoice'),
        ),
    ]
