# Generated by Django 5.1.6 on 2025-04-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('US', 'United States'), ('UK', 'United Kingdom'), ('AU', 'Australia'), ('NZ', 'New Zealand'), ('DE', 'Germany')], default='US', max_length=2, verbose_name='Country'),
        ),
    ]
