# Generated by Django 5.1.6 on 2025-04-12 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('United States', 'United States'), ('United Kingdom', 'United Kingdom'), ('Australia', 'Australia'), ('New Zealand', 'New Zealand'), ('Germany', 'Germany'), ('Canada', 'Canada')], default='US', max_length=15, verbose_name='Country'),
        ),
    ]
