# Generated by Django 5.1.6 on 2025-04-28 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crafting', '0013_remove_paymentdetail_payment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='draft', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('digitizing_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crafting.digitizingorder')),
                ('patch_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crafting.patchorder')),
                ('vector_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crafting.vectororder')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
