# Generated by Django 5.1.6 on 2025-06-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_invoice_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
