"""
Django settings for digitizingplus project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import sys

import users
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-yq@k!mpgp0@6zhr7g3wp*+60ej-88mkb()ful2_^89$1&qv!(5'

# SECURITY WARNING: don't run with debug turned on in production!


if 'runserver' in sys.argv:
    DEBUG = True
else:
    DEBUG = False

ALLOWED_HOSTS = ['www.digitizingplus.com', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'users',    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_countries',
    "crispy_forms",
    "crispy_bootstrap5",

    'frontend',
    'crafting',
    'finance',
    
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',

   
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',

        # 👇 Your middleware comes AFTER SessionMiddleware
    'users.middleware.ImpersonateUserMiddleware',
    
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'digitizingplus.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'digitizingplus.context_processors.company_info',
            ],
        },
    },
]

WSGI_APPLICATION = 'digitizingplus.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'dp',           # Your database name
        'USER': 'postgres',     # Your PostgreSQL username (default is 'postgres')
        'PASSWORD': 'admin112',  # Your PostgreSQL password
        'HOST': 'localhost',    # Or '127.0.0.1'
        'PORT': '5433',         # Default PostgreSQL port
    }
}

# if 'runserver' in sys.argv:  
#     DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.postgresql',
#             'NAME': 'dp',           # Your database name
#             'USER': 'postgres',     # Your PostgreSQL username (default is 'postgres')
#             'PASSWORD': 'admin112',  # Your PostgreSQL password
#             'HOST': 'localhost',    # Or '127.0.0.1'
#             'PORT': '5433',         # Default PostgreSQL port
#         }
#     }
# else:
#     DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.sqlite3',
#             'NAME': BASE_DIR / 'db.sqlite3',
#         }
#     }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'  # URL prefix for static files
#STATICFILES_DIRS = [BASE_DIR / 'static']
#STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

if 'runserver' in sys.argv:
    STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
else:
    STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = 'users.User'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # For development


LOGIN_URL = 'web:index' 


# EMAIL SETUP
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'digitizingpluss@gmail.com'
EMAIL_HOST_PASSWORD = 'mluz brbs guqa kfqn'  # Use App Password, not your regular password
DEFAULT_FROM_EMAIL = 'digitizingpluss@gmail.com'
SERVER_EMAIL = 'digitizingpluss@gmail.com'